#!/usr/bin/env bash
# Creates a copy of the local DB as revised_gov_db, creates user gov_local_user
# with similar privileges, and writes .envGov.
# Uses api/.env for source DB connection.
# To create DB/user you need a PostgreSQL superuser. Run ONE of:
#
# With sudo (use bash so the script need not be executable by postgres):
#   cp api/.env /tmp/gov_setup.env
#   sudo -u postgres env POSTGRES_USER=postgres GOV_PROJECT_ROOT="$(pwd)" GOV_ENV_FILE=/tmp/gov_setup.env bash "$(pwd)/setup_revised_gov_db.sh"
#
# Or with postgres password (no sudo):
#   POSTGRES_USER=postgres POSTGRES_PASSWORD=your_postgres_password ./setup_revised_gov_db.sh
set -e

# Resolve project root: use GOV_PROJECT_ROOT if set, else directory containing this script (works with sudo)
if [[ -n "$GOV_PROJECT_ROOT" ]]; then
  PROJECT_ROOT="$GOV_PROJECT_ROOT"
else
  SCRIPT_PATH="${BASH_SOURCE[0]}"
  if [[ "$SCRIPT_PATH" != /* ]]; then
    SCRIPT_PATH="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)/$(basename "$SCRIPT_PATH")"
  fi
  PROJECT_ROOT="$(dirname "$SCRIPT_PATH")"
fi
# Env file: GOV_ENV_FILE if set (e.g. /tmp/gov_setup.env when postgres can't read project), else api/.env
API_ENV="${GOV_ENV_FILE:-${PROJECT_ROOT}/api/.env}"
ENVGOV_FILE="${PROJECT_ROOT}/.envGov"
SOURCE_DB="government_projects"
TARGET_DB="revised_gov_db"
NEW_USER="gov_local_user"
NEW_PASS='Admin2020@#'
# When running as postgres (POSTGRES_USER set), use /tmp for dump so we don't need write access to project
if [[ -n "$POSTGRES_USER" ]]; then
  DUMP_FILE="/tmp/revised_gov_db_dump.sql"
else
  DUMP_FILE="${PROJECT_ROOT}/.revised_gov_db_dump.sql"
fi

if [[ ! -f "$API_ENV" ]]; then
  echo "Missing ${API_ENV}"
  echo "Tip: copy api/.env to /tmp/gov_setup.env and run with GOV_ENV_FILE=/tmp/gov_setup.env"
  exit 1
fi
source "$API_ENV"
HOST="${DB_HOST:-127.0.0.1}"
PORT="${DB_PORT:-5432}"
# Use postgres superuser for create DB/user if provided
ADMIN_USER="${POSTGRES_USER:-$DB_USER}"
ADMIN_PASS="${POSTGRES_PASSWORD:-$DB_PASSWORD}"
# When using POSTGRES_USER, use Unix socket for admin (so sudo -u postgres works without password)
if [[ -n "$POSTGRES_USER" ]]; then
  ADMIN_HOST=""
  ADMIN_PORT=""
else
  ADMIN_HOST="$HOST"
  ADMIN_PORT="$PORT"
fi

echo "--- 1) Dump source DB ${SOURCE_DB} to ${DUMP_FILE}"
export PGPASSWORD="$DB_PASSWORD"
pg_dump -h "$HOST" -p "$PORT" -U "$DB_USER" -d "$SOURCE_DB" -F p -f "$DUMP_FILE"
unset PGPASSWORD
echo "    Done."

echo "--- 2) Create database ${TARGET_DB} (drop if exists)"
export PGPASSWORD="$ADMIN_PASS"
psql ${ADMIN_HOST:+-h "$ADMIN_HOST"} ${ADMIN_PORT:+-p "$ADMIN_PORT"} -U "$ADMIN_USER" -d postgres -v ON_ERROR_STOP=1 -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '${TARGET_DB}' AND pid <> pg_backend_pid();" 2>/dev/null || true
psql ${ADMIN_HOST:+-h "$ADMIN_HOST"} ${ADMIN_PORT:+-p "$ADMIN_PORT"} -U "$ADMIN_USER" -d postgres -v ON_ERROR_STOP=1 -c "DROP DATABASE IF EXISTS ${TARGET_DB};"
psql ${ADMIN_HOST:+-h "$ADMIN_HOST"} ${ADMIN_PORT:+-p "$ADMIN_PORT"} -U "$ADMIN_USER" -d postgres -v ON_ERROR_STOP=1 -c "CREATE DATABASE ${TARGET_DB};"
echo "    Done."

echo "--- 3) Restore dump into ${TARGET_DB}"
export PGPASSWORD="$ADMIN_PASS"
psql ${ADMIN_HOST:+-h "$ADMIN_HOST"} ${ADMIN_PORT:+-p "$ADMIN_PORT"} -U "$ADMIN_USER" -d "$TARGET_DB" -v ON_ERROR_STOP=1 -f "$DUMP_FILE"
unset PGPASSWORD
echo "    Done."

echo "--- 4) Create user ${NEW_USER} and grant privileges"
export PGPASSWORD="$ADMIN_PASS"
psql ${ADMIN_HOST:+-h "$ADMIN_HOST"} ${ADMIN_PORT:+-p "$ADMIN_PORT"} -U "$ADMIN_USER" -d postgres -v ON_ERROR_STOP=1 -c "
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${NEW_USER}') THEN
      CREATE ROLE ${NEW_USER} WITH LOGIN PASSWORD '${NEW_PASS}';
    ELSE
      ALTER ROLE ${NEW_USER} WITH PASSWORD '${NEW_PASS}';
    END IF;
  END \$\$;
"
psql ${ADMIN_HOST:+-h "$ADMIN_HOST"} ${ADMIN_PORT:+-p "$ADMIN_PORT"} -U "$ADMIN_USER" -d postgres -v ON_ERROR_STOP=1 -c "GRANT CONNECT ON DATABASE ${TARGET_DB} TO ${NEW_USER};"
psql ${ADMIN_HOST:+-h "$ADMIN_HOST"} ${ADMIN_PORT:+-p "$ADMIN_PORT"} -U "$ADMIN_USER" -d "$TARGET_DB" -v ON_ERROR_STOP=1 -c "
  GRANT USAGE ON SCHEMA public TO ${NEW_USER};
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${NEW_USER};
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${NEW_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${NEW_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${NEW_USER};
"
unset PGPASSWORD
echo "    Done."

echo "--- 5) Write .envGov"
ENVGOV_CONTENT="# Connection to revised government DB (copy of local)
# Generated by setup_revised_gov_db.sh
DB_TYPE=postgresql
DB_HOST=${HOST}
DB_PORT=${PORT}
DB_NAME=${TARGET_DB}
DB_USER=${NEW_USER}
DB_PASSWORD=${NEW_PASS}
"
if printf '%s' "$ENVGOV_CONTENT" > "$ENVGOV_FILE" 2>/dev/null; then
  echo "    Written to ${ENVGOV_FILE}"
else
  FALLBACK_ENVGOV="/tmp/.envGov.revised_gov_db"
  printf '%s' "$ENVGOV_CONTENT" > "$FALLBACK_ENVGOV"
  echo "    Could not write to project; copied to ${FALLBACK_ENVGOV}"
  echo "    Run: cp ${FALLBACK_ENVGOV} ${ENVGOV_FILE}"
fi

echo "--- 6) Remove temporary dump file"
rm -f "$DUMP_FILE"
echo "    Done."

echo "Summary:"
echo "  Database: ${TARGET_DB} (copy of ${SOURCE_DB})"
echo "  User: ${NEW_USER}"
echo "  Config: ${ENVGOV_FILE}"
echo "To use: source .envGov or copy vars into your app (e.g. api/.env for revised DB)."
